syntax = "proto3";

package flavor.v1;

import "flavor/v1/common.proto";
import "flavor/v1/inspector.proto";

service ForwardService {
  rpc Forward(ForwardRequest) returns (stream ForwardResponse);
  rpc Proxy(ProxyRequest) returns (stream ProxyResponse);
}

message ProxyRequest {
  string listen = 1;
}

message ProxyStarted {
  string listen_address = 1;
}

message ProxyResponse {
  oneof event {
    ProxyStarted started = 1;
    ForwardConnection opened = 2;
    ForwardConnection closed = 3;
    ForwardRefused refused = 4;
  }
}

message ForwardRequest {
  string destination = 1;
  string listen = 2;
  string network = 3;
}

message ForwardRoute {
  InspectDestinationResponse decision = 1;
  NetworkRef network = 2;
  string target = 3;
}

message ForwardStarted {
  string listen_address = 1;
  ForwardRoute route = 2;
}

message ForwardConnection {
  uint64 id = 1;
  string client = 2;
  ForwardRoute route = 3;
  uint64 bytes_sent = 4;
  uint64 bytes_received = 5;
  string destination = 6;
}

message ForwardRefused {
  uint64 id = 1;
  string client = 2;
  FlavorErrorDetail reason = 3;
  string destination = 4;
}

message ForwardResponse {
  oneof event {
    ForwardStarted started = 1;
    ForwardConnection opened = 2;
    ForwardConnection closed = 3;
    ForwardRefused refused = 4;
  }
}
